
set(WITH_SYSTEMD_DESC "Build with systemd support")
option(WITH_SYSTEMD ${WITH_SYSTEMD_DESC} ON)
if(OS_LINUX)
  add_feature_info(WITH_SYSTEMD WITH_SYSTEMD ${WITH_SYSTEMD_DESC})
else()
  set(WITH_SYSTEMD OFF)
endif()

set(USE_AIO_POLL_DESC "Build using aio poll instead of epoll")
option(USE_AIO_POLL ${USE_AIO_POLL_DESC} ON)
if(OS_LINUX)
  add_feature_info(USE_AIO_POLL USE_AIO_POLL ${USE_AIO_POLL_DESC})
else()
  set(USE_AIO_POLL OFF)
endif()
